version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: mimic-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mimic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - mimic-network

volumes:
  postgres_data:
    name: mimic_postgres_data

networks:
  mimic-network:
    name: mimic-network

